use chrono::{DateTime, NaiveDate, Utc};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, JsonSchema, ToSchema)]
pub struct DailyFactorSnapshot {
    pub trade_date: NaiveDate,
    pub industry: Option<String>,
    pub adj_close: Option<f64>,
    pub close_raw: Option<f64>,
    pub adj_factor: Option<f64>,
    pub ret_1d: Option<f64>,
    pub ret_5d: Option<f64>,
    pub ret_10d: Option<f64>,
    pub ret_20d: Option<f64>,
    pub ret_60d: Option<f64>,
    pub ret_120d: Option<f64>,
    pub volatility_20d: Option<f64>,
    pub volatility_60d: Option<f64>,
    pub downside_volatility_20d: Option<f64>,
    pub max_drawdown_20d: Option<f64>,
    pub max_drawdown_60d: Option<f64>,
    pub ma5: Option<f64>,
    pub ma10: Option<f64>,
    pub ma20: Option<f64>,
    pub ma60: Option<f64>,
    pub ma_distance_20: Option<f64>,
    pub ma_distance_60: Option<f64>,
    pub rsi14: Option<f64>,
    pub macd_dif: Option<f64>,
    pub macd_dea: Option<f64>,
    pub macd_bar: Option<f64>,
    pub bb_mid: Option<f64>,
    pub bb_up: Option<f64>,
    pub bb_low: Option<f64>,
    pub bb_width: Option<f64>,
    pub atr14: Option<f64>,
    pub turnover_rate: Option<f64>,
    pub turnover_mean_20d: Option<f64>,
    pub amount_mean_20d: Option<f64>,
    pub volume_ratio: Option<f64>,
    pub amplitude_20d: Option<f64>,
    pub pe_ttm: Option<f64>,
    pub peg_ttm: Option<f64>,
    pub pb: Option<f64>,
    pub ps_ttm: Option<f64>,
    pub dv_ttm: Option<f64>,
    pub total_mv: Option<f64>,
    pub circ_mv: Option<f64>,
    pub dist_to_high_252d: Option<f64>,
    pub dist_to_low_252d: Option<f64>,
    pub pe_ttm_pctile_756d: Option<f64>,
    pub pb_pctile_756d: Option<f64>,
    pub revenue_yoy: Option<f64>,
    pub net_profit_yoy: Option<f64>,
    pub roe: Option<f64>,
    pub gross_margin: Option<f64>,
    pub debt_asset_ratio: Option<f64>,
    pub ocf_to_net_profit: Option<f64>,
    pub latest_report_date: Option<NaiveDate>,
    pub latest_notice_date: Option<NaiveDate>,
    pub news_count_7d: Option<i32>,
    pub announcement_count_30d: Option<i32>,
    pub risk_warning: bool,
    pub bar_count_60d: Option<i32>,
    pub metrics_present: bool,
    pub financial_stale_days: Option<i32>,
    pub data_gaps_detected: bool,
    pub computed_at: DateTime<Utc>,
}
